language: android
android:
  components:
    - build-tools-22.0.1
    - android-23
    - extra

  licenses:
    - 'android-sdk-license.*'

# Emulator Management: Create, Start and Wait
before_script:
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - android list target
  - ./gradlew connectedAndroidTest

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/






